vpython/vpython-jupyter

- CONTRIBUTORS.md
- vpython/with_notebook.py
When I used vpython on jupyter notebook, I faced a problem that a vpython kernel running on a remote server kept using 100% CPU. After surveying, I found the CPU spin was caused by asyncio.sleep(0) function. This issue ( https://github.com/python/asyncio/issues/398 ) describes the problem in detail.
To solve the problem, simply waiting longer than zero works well; the CPU usage changes from 100% to 1%. Of course, this change does not harm the performance of vpython in my sense.
> Avoid 100% CPU on asyncio.sleep(0)

- vpython/vpython.py
This fixes a couple of problems with scene and removes a debugging `print`.
> Several fixes to scene and remove print from debugging

- appveyor.yml
`patch` is now available only in the `free` channel. Including that channel can slow down conda quite a bit so I want to avoid it if possible.
FIxes #22
> Remove patch as a dependency on windows

- vpython/_notebook_helpers.py
Fixes #19 (tested this locally)
> Get spyder config item in way that works when item does not exist

- requirements.txt
- setup.py
- vpython/with_notebook.py
Made a few modifications to get VPython to work on JupyterHub and Binder.
> VPython support on JupyterHub and Binder

- .travis.yml
- CONTRIBUTORS.md
- vpython/vpython.py
Originally, the `__del__` function of `gobj` called `super(gcurve, self).__del__()`, while `gcurve` is inherited from `gobj`, so `gobj.__del__()` is being called, again. 
This caused an infinite loop, resulted in `RecursionError`, as the recursion depth limit of Python was hit.
I think this is a typo, and `super(gobj, self).__del__()` is what we expect.
Using the original code, the error can be reproduced with just two lines of code:
```python3
from vpython import *
curve1 = gcurve()
```
After closing the browser, Python deleted the `curve1` object, and thus triggered the bug.
> Calling correct delete function on deletion of gobj

- vp_copy.yaml
The purpose of these builds is to automatically copy the couple of packages we need from conda-forge to the vpython conda channel.
This can be merged whenever it passes.
> Fix the cron builds

- .github/workflows/upload_pypi.yml
Wheels on linux require a build configuration I've never understood. We weren't building wheels on linux before, so we won't here either (the linux wheel uploads were failing because of incorrect build configuration).
> Fix wheels on linux yet

- .github/workflows/upload_pypi.yml
Apparently this builds lots of wheels and then tries to upload all of them. we only want the vpython ones...
> Only upload vpython wheels

- .github/workflows/copy_conda_packages.yml
- vp_copy.yaml
This replaces what was done during travis cron jobs and adds vpython itself to the list of conda packages that are copied.
> Add workflow to copy packages 

- vpython/no_notebook.py
qt doesn't work on Windows for now because of issues with multiprocessing. This adds an explicit error if the user tries it.
> Add explicit error if the browser is set to qt on windows

- Demos_no_notebook/HardSphereGas.py
- vpython/rate_control.py
- vpython/vpython.py
This removes one more use of `time.clock` from a demo program and simplifies setting up vpython's `clock`. Since `perf_counter` was introduced in Python 3.3 and we support 3.5 and up we shouldn't need the `try`/`except`.
> A little more clock cleanup

- vpython/no_notebook.py
@atitus -- the qt browser fails on python 3.8 because of a change in multiprocessing I think (see #74). This workaround just raises an explicit error message in that case.
> qt fails on python 3.8 and up, so raise a better error message

- vpython/no_notebook.py
Hi, the change basically prevents calling `os.kill` on Windows while running inside Spyder and instead just raise a `KeyboardInterrupt`
Fixes spyder-ide/spyder#12300
~~The missing thing here is add a way to prevent showing the traceback generated by raising the exception inside Spyder.~~
Pinging  @ccordoba12 just in case
> PR: Don't call os.kill on Windows if running inside Spyder

- .github/workflows/copy_conda_packages.yml
The most recent run of the workflow that copies packages from conda-forge to our channel. I'm hoping that upgrading to the latest version of the github action that installs miniconda does the trick.
> Update to latest version of miniconda action in cron job

- .github/workflows/upload_pypi.yml
`cryptography` needs rust to build, and but rust doesn't provide a wheel on Python 3.8.
> Add rust to manylinux build

- vpython/vpython.py
- Let Python do its work and use default and regular arguments instead of `*args`
- Use `TypeError` instead of `AttributeError`
- `".png" in "name.png.jpg"` will return `True`, instead we need to check the last four characters
- `include_labels` is now set to `"T"` explicitly via `capture_labels=True`
- Format code for better readability: add new lines after `:`, add whitespaces around `+`
> Improve the `capture` implementation and fix its bugs

- .github/workflows/copy_conda_packages.yml
- vp_copy.yaml
This should fix the conda install issue for people using the `vpython` conda channel
> Add python_abi to vpython channel

- .github/workflows/build.yml
- .github/workflows/upload_pypi.yml
- vpython/test/test_namespace.py
This does two things:
1. Add Python 3.9 to the list of versions that we test/upload to PyPI
2. Remove Python 3.6 from the list of versions we test/upload.
> Update Python versions in CI

- CONTRIBUTORS.md
- vpython/__init__.py
Fixed version check to also encompass 3.10. The prior check to see if notebook was required was equivalent to `'1' < '5'` when the Python version was 3.10 or greater.
edit: FIxes #173
> Fixed version check to encompass Python 3.10

- .github/workflows/build.yml
- .github/workflows/upload_pypi.yml
- setup.py
- vpython/__init__.py
- vpython/vpython.py
> Updates for Python 3.10 and some housecleaning

- vpython/vpython.py
When I removed `_ispython3` in #180 I accidentally broke some code that used that. This pull request should fix that.
> Remove references to _ispython3

- .github/workflows/copy_conda_packages.yml
This can be merged as soon as it passes. Copying packages to our own conda channel was broken for a while because they now require cloning using `https` and we were doing that.
> Use https instead of git for clone

- vpython/no_notebook.py
This partially addresses #217, by (optionally) not launching a browser and restricting the http port to a specified port.
This allows development with an open browser on a certain port, rather than having your default browser relaunched every time you run the code.
The relevant behavior is specified by two environment vars:
VPYTHON_HTTP_PORT
and
VPYTHON_NO_LAUNCH_BROWSER
> rebase patch for VPYTHON_HTTP_PORT and VPYTHON_NO_LAUNCH_BROWSER

- vpython/cyvector.pyx
A follow up to #231, this PR udpates the `cyvector.__repr__` method to follow the Python convention.
> cyvector.__repr__ method now follows convention

- .github/dependabot.yml
This pull request essentially adds a new GItHub action which checks whether our GitHub actions are up-to-date. This has become the standard way to keep with the rap[idly changing set of version numbers in our workflows.
Once merged, it will open pull requests to increment version numbees where needed.
> Add auto-updates of GH actions with dependabot

- vpython/cyvector.pyx
The current codebase has this comment regarding the lack of `__rmul__` in `cyvector.pyx`:
```py
def __mul__(self, other):  ## in cython order of arguments is arbitrary, rmul doesn't exist
if isinstance(other, (int, float)):
return vector(self._x * other, self._y * other, self._z * other)
elif isinstance(self, (int, float)):
return vector(self * other._x, self * other._y, self * other._z)
return NotImplemented
```
However, when cython is not installed the following will throw a `TypeError` due to a lack of ``__rmul``:
```py
1.0 * vector(3, 4, 8)
```
This contradicts the following statement in the README:
> If you don't have a compilier vpython should __still work__, but code that generates a lot of vectors may run a little slower.
The commit attached to this PR ensures the `__rmul__` seen …
> Fix TypeError resulting from lack of __rmul__

- setup.py
Install the latest version of jupyterlab-vpython extension.
> install_requires jupyterlab-vpython >= 3.1.7
