.travis.yml
setup.py

Hopefully the first commit here will fail so I know that the check I added actually tests something...if so, I'll fix it.

Set the type (markdown) of README

---

labextension/vpython/package.json
labextension/vpython/src/glowcommlab.d.ts
labextension/vpython/src/glowcommlab.js
labextension/vpython/src/index.ts
requirements.txt
vpython/vpython_libraries/glowcomm.js

Added support for websockets through a proxied server. This will enable vpython to work on Binder and other proxied servers such as JupyterHub.

Add websocket support through proxied server

---

.travis.yml
drive_copy.py

This will hopefully fix the breaking travis CRON jobs. Either way, I'll merge when tests pass and then release 7.5.2.

Try fixing the travis CRON jobs

---

vpython/_notebook_helpers.py

This fixes #42; turns out there was not much to be fixed!

Accommodate change in spyder 4

---

.travis.yml
appveyor.yml
vpython/vpython_libraries/glowcomm.js

In addition to the fix, this adds python 3.8 to the builds.

Fix 7.6.0 for jupyter notebook 

---

.github/workflows/build.yml

Meant to do this before merging the other PR...

Make push trigger builds too

---

.github/workflows/upload_pypi.yml

Turns out indentation matters...

Fix bad yaml

---

.github/workflows/upload_pypi.yml

Hopefully this is the last fix...

Remove unnecessary wheel build

---

.github/workflows/copy_conda_packages.yml

Run cron job daily instead of hourly

---

README.md
RELEASE.md

Add dev install instructions and release instructions

---

labextension/vpython/package.json
labextension/vpython/src/glowcommlab.js

Made small changes for the vpython labextension for jupyterlab that works with vpython 7.6.1.

Jupyterlab vpython 7.6.1 updates

---

Demos_no_notebook/qt.py

Really this is just to give another commit that can be tagged as 7.6.1 🙄

Add minor change to qt.py

---

labextension/vpython/src/glowcommlab.js
vpython/rate_control.py
vpython/vpython.py
vpython/vpython_libraries/glowcomm.html
vpython/vpython_libraries/glowcomm.js

Changed from 30 renders/s to 60 renders/s. Fixed scene.camera.follow(None). Enabled visible attribute of graph objects. Addressed serious event ordering in the case of waiting for pick or compound.

Improve responsiveness; fix bugs

---

labextension/vpython/README.md
labextension/vpython/package-lock.json

I tested all the notebooks in lab and they all do the same thing in lab as they do in notebook. ;-)
Usually, it appears to be the right thing.

Merged audit fix and dependabot fixes from August and September into a single PR.

---

vpython/cyvector.pyx

cannot copy object, need to copy attrs

---

.github/workflows/copy_conda_packages.yml

Hopefully this will fix the package copying...

Fix miniconda setup (again!)

---

labextension/vpython/package.json
labextension/vpython/src/glowcommlab.js
labextension/vpython/src/index.ts

Made changes so that VPython JupyterLab Extension works with JuptyerLab 2.

Added support for JupyterLab 2

---

labextension/vpython/src/glowcommlab.js
vpython/vpython_libraries/glowcomm.html
vpython/vpython_libraries/glowcomm.js

Reinstated some canvas code to get the vpython extension for jupyterlab to work.

Put back some code related to canvas.

---

labextension/vpython/src/glowcommlab.js
vpython/vpython_libraries/glowcomm.html
vpython/vpython_libraries/glowcomm.js

Added a check to see if we are running in jupyterlab when a canvas is created.

Added isjupyterlab_vpython check

---

labextension/vpython/package.json
labextension/vpython/src/glowcommlab.js

Made changes so that jupyterlab vpython extension works on JupyterHub and MyBinder.

Update jupyterlab vpython to work on JupyterHub and MyBinder

---

README.md

Changes the badge from travis to github

Fixed status badge in README

---

.github/workflows/build.yml
.github/workflows/upload_pypi.yml
CONTRIBUTORS.md

Add linux aarch64 wheel build support. 
Related to https://github.com/vpython/vpython-jupyter/issues/182 @BruceSherwood Could you please review this PR?

Add linux aarch64 wheel build support

---

setup.py

Quick fix for autobahn version problem.

add version guard for autobahn

---

.gitmodules

Added jupyterlab-vpython extension as a submodule to the main vpython-jupyter project. See the following for the basics of git submodules.
https://gist.github.com/gitaarik/8735255

created submudule for jupyterlab-vpython in labextension directory

---

CONTRIBUTORS.md

This adds Danny Staple and fixes a typo in the list of contributors.

Fix contributor typo and add missing contributor

---

setup.py

Added jupyterlab-vpython to install-requires dependency list in setup.py

add jupyterlab-vpython to install-requires list
